### ISSUE TITLE
Tests for all available PHP versions

### ISSUE THREAD

**Issue by pwlap** [gkawka/geckoboard-dataset-api#2]
Goal
---
Repo has tests for all available PHP versions (`"^5.3"`). We can use [Travis-ci](https://travis-ci.com/) for open-source repositiories. 

Bug example
---
I found possible bug in [DataBuiilder implementation](https://github.com/gkawka/geckoboard-dataset-api/blob/master/src/DatasetBuilder.php#L15-L17) where is using declaration from higher PHP version.

**Comment by gkawka** [comment]
Good point. Upgraded php deps to php5.5 and added travis and scrutinizer integration 👍
