### ISSUE TITLE
Declare field indentifier in TypeInterface

### ISSUE THREAD

**Issue by pwlap** [gkawka/geckoboard-dataset-api#4]
Goal
---
TypeInterface contains information on field identifier. It simplifies API on DatasetBuilder by remove `id parameter` [on addField() method](https://github.com/gkawka/geckoboard-dataset-api/blob/master/src/DatasetBuilder.php#L27)

Example
---
```php
interface TypeInterface
{
    // ...

    /**
     * Return type identifier
     *
     * @return string
     */
    public function getName();
}
```
```php
class DatasetBuilder
{
    // ...

    public function addField(TypeInterface $fieldDefinition)
    {
        $this->fields[$fieldDefinition->getName()] = $fieldDefinition->toArray();

        return $this;
    }
```

**Comment by gkawka** [comment]
On the other hand it could complicate adding data to DataRow but feel free to contribute if you have idea how to implement this without complicating project ;)
