### ISSUE TITLE
Add proper licensing

### ISSUE THREAD

**Issue by zsiciarz** [gkawka/geckoboard-dataset-api#5]
No license means [implicit copyright](https://blog.codinghorror.com/pick-a-license-any-license/). Consider adding a permissive license, such as MIT, BSD or Apache. This may be helpful when making the choice: https://tldrlegal.com/

**Comment by gkawka** [comment]
Added MIT at https://github.com/gkawka/geckoboard-dataset-api/commit/0138c703d4b0722f34c8325cf66c9e5029d18618. Thanks for reminder 👍
